version: "3.5"
services:
  db.adamperyman.com:
    container_name: db.adamperyman.com
    image: adamperyman/happy-mongodb:latest
    networks:
      - adamperyman.com
    ports:
      - 27017:27017
    env_file:
      - .env
    environment:
      - AUTH=yes
    volumes:
      - /data/adamperyman:/data/db
  api.adamperyman.com:
    container_name: api.adamperyman.com
    image: adamperyman/api.adamperyman.com:latest
    networks:
      - adamperyman.com
    build: .
    env_file:
      - .env
    ports:
      - 4000:4000
  adamperyman.com:
    container_name: adamperyman.com
    image: adamperyman/adamperyman.com:latest
    networks:
      - adamperyman.com
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
networks:
  adamperyman.com:
    driver: bridge
